//svg3dtagcloud.js,生成3D标签云,因cpu占用过高而弃用了
$(document).ready(function () {
    var entries = [
        { label: 'MyGalgame', url: 'http://www.mygalgame.com/', target: '_blank' },
        { label: 'ZodGame', url: 'https://www.zodgame.us/', target: '_blank' },
        { label: '里番屋', url: 'http://www.lifanroom.com/', target: '_blank' },
        { label: '绅士仓库', url: 'https://cangku.in/', target: '_blank' },
        { label: 'EroACG', url: 'http://www.eroacg.com/', target: '_blank' },
        { label: 'ACGTracker', url: 'http://acgtracker.com/', target: '_blank' },
        { label: '萌命缘', url: 'http://www.mmy.moe/forum.php', target: '_blank' },
        { label: '次元の圣光', url: 'https://www.acglover.top/', target: '_blank' },
        { label: '爱恋BT', url: 'http://www.kisssub.org/', target: '_blank' },
        { label: '喵窝', url: 'http://yui-nya.com/', target: '_blank' },
        { label: '樱花漫舍', url: 'http://www.oomoe.org/', target: '_blank' },
        { label: '纯爱计划', url: 'https://goo.gl/', target: '_blank' },
        { label: '绅士ACG社', url: 'http://www.htacgs.com', target: '_blank' },
        { label: '轻萌社', url: 'http://nacg.me/', target: '_blank' },
        { label: '圣灵神域', url: 'ttps://bbs.holyo.org', target: '_blank' },
        { label: '次元老司机', url: 'http://www.l-sj.cc/', target: '_blank' },
        { label: '最ACG', url: 'http://www.zuiacg.com/', target: '_blank' },
        { label: '玖爱萌动漫', url: 'https://9iacg.com', target: '_blank' },
        { label: '里番萌', url: 'https://lifanmoe.com', target: '_blank' },
        { label: '超级硬', url: 'https://cjy.im', target: '_blank' },
        { label: '本子社', url: 'http://www.benzishe.net/', target: '_blank' },
        { label: '吉人动漫网', url: 'http://jren100.moe/', target: '_blank' },
        { label: 'CAOFREE', url: 'http://caofree.com/', target: '_blank' },
        { label: '面码buster', url: 'https://ht.acgbuster.com/', target: '_blank' },
        { label: '福利次元', url: 'https://www.fuliciyuan.com/', target: '_blank' },
        { label: '绅士の乡', url: 'http://acg18.cc/', target: '_blank' },
        { label: '喵哆啦', url: 'http://www.nyadora.com/', target: '_blank' },
        { label: 'G车库', url: 'https://www.galgame.lol/', target: '_blank' },
        { label: '绅士社区', url: 'https://www.shenshiacg.com/', target: '_blank' },
        { label: '里次元', url: 'https://loli.cool/', target: '_blank' },
        { label: 'bilibili动漫网', url: 'https://99kjy.com/', target: '_blank' },
        { label: 'UOCO妹子图库', url: 'https://uoco.co', target: '_blank' },
        { label: 'ACGN多看', url: 'http://acgn.dk/', target: '_blank' },
        { label: '绅士ACG', url: 'http://hentaiacg.club/forum.php', target: '_blank' },
        { label: '绅士二次元', url: 'https://www.acg.tf', target: '_blank' },
        { label: '九萌社', url: 'http://9meng.cc', target: '_blank' },
        { label: '好萌在线里番', url: 'https://nicemoe.com', target: '_blank' },
        { label: '零の绅士计划', url: 'http://exacg.5awo.com/', target: '_blank' },
        { label: '梦之圈资源站', url: 'http://www.oomoe.org/', target: '_blank' },
        { label: '帝之冰魂动漫', url: 'http://www.dzbhdm.com/', target: '_blank' },
        { label: '萝莉RBQ', url: 'http://lolirbq.55555.io', target: '_blank' },
        { label: 'AES、紳士', url: 'http://aeshxanime.com', target: '_blank' },
        { label: '嗶咔嗶咔漫畫', url: 'http://picacomic.com/', target: '_blank' },
        { label: '汗汗漫画', url: 'http://www.hanhan88.com/', target: '_blank' },
        { label: '绅士の社交场', url: 'http://acghentai.club/', target: '_blank' },
        { label: '绯月Galgame', url: 'http://bbs.2dgal.com/', target: '_blank' },
        { label: 'ACG.BZ', url: 'http://acg.bz/', target: '_blank' },
        { label: '里番儿', url: 'http://bbs.north-plus.net/', target: '_blank' },
        { label: 'North+', url: 'http://www.benzishe.net/', target: '_blank' },
        { label: '和諧區', url: 'http://hexiequ.com/', target: '_blank' },
        { label: 'CE家族社', url: 'https://cefamilie.com/', target: '_blank' },
        { label: '萌幻之乡', url: 'http://www.moe-acg.cc/', target: '_blank' },
        { label: '69ACG', url: 'http://69acg.me/', target: '_blank' },
        { label: 'Hgamecn', url: 'http://www.hgamecn.com/', target: '_blank' },
        { label: '漫社堂', url: 'http://www.comicst.com/', target: '_blank' },
        { label: '紳士漫畫', url: 'http://www.wnacg.org/', target: '_blank' },
        { label: '萌啦', url: 'http://www.moe.la/', target: '_blank' },
        { label: 'Galgame@PC6', url: 'http://www.pc6.com/pc/galgame/', target: '_blank' },
        { label: '404ACG', url: 'http://pan.404acg.com/Index/Lists/', target: '_blank' },
        { label: '绅士图书馆', url: 'http://htai.me/', target: '_blank' },
        { label: '紳士の庭', url: 'http://gmgard.us/', target: '_blank' },
        { label: 'Cosersuki', url: 'http://cosersuki.org/', target: '_blank' },
        { label: '天使二次元', url: 'https://www.tianshi2.com/', target: '_blank' },
        { label: 'アキバBlog', url: 'http://blog.livedoor.jp/geek/', target: '_blank' },
        { label: 'Moeyo', url: 'http://www.moeyo.com/', target: '_blank' },
        { label: 'Getchu', url: 'http://www.akibablog.net/', target: '_blank' },
        { label: '魁!!同人塾', url: 'http://www.erojima2.com/', target: '_blank' },
        { label: 'KISS-SUB !X3', url: 'http://forum.kiss-sub.net/', target: '_blank' },
        { label: '美少女☆萌え', url: 'http://bishoujo.moe/', target: '_blank' },
        { label: 'MOEMILK', url: 'http://www.moemilk.com/', target: '_blank' },
        { label: 'アキバHOBBY', url: 'http://akibahobby.net/', target: '_blank' },
        { label: 'アダルト蛇屋', url: 'http://adulthebiya.blog36.fc2.com/', target: '_blank' },
        { label: '同人萌え書庫', url: 'http://doujinmoesyoko.blog.fc2.com/', target: '_blank' },
        { label: '萌え速報', url: 'http://otanews.livedoor.biz/', target: '_blank' },
        { label: '萌えドロイド', url: 'https://moedroid.jp/', target: '_blank' },
        { label: 'わくてか速報', url: 'http://blog.livedoor.jp/wakusoku/', target: '_blank' },
        { label: 'にゅーあきば', url: 'http://www.new-akiba.com/', target: '_blank' },
        { label: 'でちゃもれ速報', url: 'http://dechamore.net/', target: '_blank' },
        { label: 'せなかBlog', url: 'http://www.senakablog.com/', target: '_blank' },
        { label: 'GameWith', url: 'http://gamewith.jp/', target: '_blank' },
        { label: '虹萌☆Ｍ', url: 'http://blog.livedoor.jp/nizimoe/', target: '_blank' },
        { label: 'NTR BLOG', url: 'http://ntrblog.com', target: '_blank' },
        { label: '二次萌エロ画像', url: 'http://moeimg.net/', target: '_blank' },
        { label: '二次元ポケット', url: 'http://niji-gazo.com/', target: '_blank' },
        { label: '二次元エロ画像', url: 'http://nijiero-ch.com/', target: '_blank' },
        { label: 'NiZi1', url: 'http://nizi1.com/', target: '_blank' },
        { label: 'NiJiEro', url: 'http://nijiero.com/', target: '_blank' },
        { label: '虹色でいず', url: 'http://www.nijiiro-days.com/', target: '_blank' },
        { label: 'EroIDO', url: 'https://eroido.jp/', target: '_blank' },
        { label: '2d-EroIDO', url: 'http://www.2d-erocafe.com/', target: '_blank' },
        { label: 'E-Hentai', url: 'http://e-hentai.org/', target: '_blank' },
        { label: 'Akiba-Online', url: 'https://www.akiba-online.com/', target: '_blank' },
        { label: 'TheDoujin', url: 'http://thedoujin.com/', target: '_blank' },
        { label: 'Hentai.ms', url: 'http://www.hentai.ms/', target: '_blank' },
        { label: 'Pururin', url: 'http://pururin.com/', target: '_blank' },
        { label: 'MOE+', url: 'http://moeiso.me/', target: '_blank' },
        { label: 'Doujin-moe', url: 'http://www.doujin-moe.us/', target: '_blank' },
        { label: 'Hmovie-moe', url: 'http://www.h-moe.com/', target: '_blank' },
        { label: 'Sukebei@Nyaa', url: 'http://sukebei.nyaa.se/', target: '_blank' },
        { label: '東京 図書館', url: 'http://tokyotosho.info/', target: '_blank' },
        { label: 'Hentai.ms', url: 'http://hentai.ms/', target: '_blank' },
        { label: 'Hentai Display', url: 'http://www.hentaidisplay.com/', target: '_blank' },
        { label: 'Hentai4Daily', url: 'http://hentai4daily.com', target: '_blank' },
        { label: 'Hentaicore', url: 'http://www.hentaicore.net/', target: '_blank' },
        { label: 'Anime Pictures', url: 'https://anime-pictures.net/', target: '_blank' },
        { label: 'Rule 34', url: 'http://rule34.xxx/', target: '_blank' },
        { label: 'E次元', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=galgame', target: '_blank' },
        { label: 'galgame', url: 'http://blog.livedoor.jp/nizimoe/', target: '_blank' },
        { label: '里漫', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=%E9%87%8C%E6%BC%AB', target: '_blank' },
        { label: '奴隶兔与安东尼吧', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=%E5%A5%B4%E9%9A%B6%E5%85%94%E4%B8%8E%E5%AE%89%E4%B8%9C%E5%B0%BC', target: '_blank' },
        { label: '后宫动漫吧', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=%E5%90%8E%E5%AE%AB%E5%8A%A8%E6%BC%AB', target: '_blank' },
        { label: '百合动漫吧', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=%E7%99%BE%E5%90%88%E5%8A%A8%E6%BC%AB', target: '_blank' },
        { label: '里番动画吧', url: 'http://tieba.baidu.com/f?ie=utf-8&amp;kw=%E9%87%8C%E7%95%AA%E5%8A%A8%E7%94%BB', target: '_blank' },
        { label: 'e绅士吧', url: 'http://nijiero.com/', target: '_blank' },
        { label: 'Pixiv', url: 'http://www.pixiv.net/', target: '_blank' },
        { label: 'yande.re', url: 'https://yande.re/', target: '_blank' },
        { label: 'AC匿名版', url: 'http://h.nimingban.com/', target: '_blank' },
        { label: '光驱岛', url: 'http://h.koukuko.com/', target: '_blank' },
        { label: 'Saraba1st', url: 'http://bbs.saraba1st.com/2b/', target: '_blank' },
        { label: '日本双马尾协会', url: 'http://twintail-japan.com/', target: '_blank' },
        { label: 'Sankaku', url: 'https://www.sankakucomplex.com/', target: '_blank' },
        { label: '18ACG', url: 'http://www.18acg.wang/', target: '_blank' },
        { label: '通用每週番組', url: 'http://uwps.magn.space/', target: '_blank' },
        { label: '进击のOWO', url: 'https://img.kiteorg.com', target: '_blank' },
        { label: 'ACG御宅世界', url: 'http://www.acgyzsj.top/', target: '_blank' },
        { label: 'kico次元导航', url: 'http://www.kicokico.com', target: '_blank' },
        { label: 'Hpoi 手办维基', url: 'http://www.hpoi.net', target: '_blank' },
        { label: 'Moe321萌站', url: 'http://www.moe321.com/', target: '_blank' },
        { label: '哥特萝莉社', url: 'http://www.gtloli.com/forum.php', target: '_blank' },
        { label: '隐士猫', url: 'https://www.yeraph.com/', target: '_blank' },
        { label: '二次元圣地', url: 'http://bbs.tohkalove.com', target: '_blank' },
        { label: '荟玩手办鉴别', url: 'http://db.buycolle.com', target: '_blank' },
        { label: '蝶梦文字游戏', url: 'http://www.iwzyx.com', target: '_blank' },
        { label: '呢哩呢哩', url: 'https://www.nilinili.top/', target: '_blank' },
        { label: '二次元图文', url: 'http://www.ecy.tw', target: '_blank' },
        { label: '星萌次元', url: 'http://www.ercy.vip/', target: '_blank' },
        { label: '夜樱梦境', url: 'http://www.nightdream.cc', target: '_blank' },
        { label: '萌系弹幕网', url: 'http://www.moemis.com/', target: '_blank' },
        { label: '追番儿', url: 'http://zhui.fr/', target: '_blank' },
        { label: '次元狗', url: 'http://www.ciyuangou.com', target: '_blank' },
        { label: 'EOCOCO', url: 'http://eoco.co/', target: '_blank' },
        { label: '噼哩噼哩', url: 'http://piliacg.com', target: '_blank' },
        { label: 'sora社', url: 'http://www.myrbq.com/', target: '_blank' },
        { label: '嘀动漫', url: 'https://www.didm.cc/', target: '_blank' },
        { label: 'ChromeFor', url: 'https://www.chromefor.com/', target: '_blank' },
        { label: '一米八动漫', url: 'https://emi8.com', target: '_blank' },
        { label: 'poi~', url: 'http://www.ipoi.cc/', target: '_blank' },
        { label: 'ACG门户', url: 'https://www.acgmh.com/', target: '_blank' },
        { label: 'E-Hentai', url: 'http://e-hentai.org/', target: '_blank' },
        { label: 'Akiba-Online', url: 'https://www.akiba-online.com/', target: '_blank' }
    ];
    var settings = {
        entries: entries,
        width: 250,
        height: 250,
        radius: '65%',
        radiusMin: 65,
        bgDraw: false,
//                bgColor: '#fff',
        opacityOver: 1.00,
        opacityOut: 0.08,
        opacitySpeed: 6,
        fov: 800,
        speed: 0.5,
        fontFamily: 'Oswald, Arial, sans-serif',
        fontSize: '12',
        fontColor: '#ff69b4f5',
        fontWeight: 'normal',//bold
        fontStyle: 'normal',//italic
        fontStretch: 'normal',//wider, narrower, ultra-condensed, extra-condensed, condensed, semi-condensed, semi-expanded, expanded, extra-expanded, ultra-expanded
        fontToUpperCase: true
    };
});